### ISSUE TITLE
Kibit IO Exception

### ISSUE THREAD

**Issue by n2o** [zmsp/sonar-clojure#4]
Thanks for fixing the last issue, but now I have another one. I get a Kibit IO Exception when I try to use your plugin. I did a `lein clean` before `sonar-scanner`, but this did not change anything. Running the analyzers with Leiningen has no problems (`lein do clean, eastwood, kibit`). Do you have any idea what is going wrong?

```
[...]
INFO: 89 files indexed
INFO: 4964 files ignored because of inclusion/exclusion patterns
INFO: Sensor Sonar-Sonargraph-Plugin [3.5] [Sonargraph]
INFO: ----------------------------------------------------------------
INFO: Sonargraph: Skipping project discuss [discuss:develop], since no Sonargraph rules are activated in current SonarQube quality profile.
INFO: ----------------------------------------------------------------
INFO: Sensor Sonar-Sonargraph-Plugin [3.5] [Sonargraph] (done) | time=2ms
INFO: Sensor InspectClojureSensor [InspectClojure]
INFO: Clojure project detected, running sonar-clojure
INFO: ●▬▬▬▬▬▬▬▬▬● Running file finder ●▬▬▬▬▬▬▬▬▬●
INFO: ●▬▬▬▬▬▬▬▬▬● Running Eastwood ●▬▬▬▬▬▬▬▬▬●
INFO: Compiling ClojureScript...
INFO: Compiling "resources/public/js/compiled/discuss.js" from ["src"]...
INFO: Successfully compiled "resources/public/js/compiled/discuss.js" in 33.042 seconds.
INFO: Compiling "resources/public/js/compiled/testable.js" from ["src"]...
INFO: Successfully compiled "resources/public/js/compiled/testable.js" in 20.137 seconds.
INFO: == Eastwood 0.2.4 Clojure 1.9.0-alpha15 JVM 1.8.0_131
INFO: Directories scanned for source files:
INFO:   src/discuss src/test test
INFO: == Warnings: 0 (not including reflection warnings)  Exceptions thrown: 0
INFO: ●▬▬▬▬▬▬▬▬▬● Running Kibit ●▬▬▬▬▬▬▬▬▬●
ERROR: ▂▃▅▇█▓▒░ KIBIT IO EXCEPTION  ░▒▓█▇▅▃▂
java.lang.NullPointerException: null
	at org.sonar.plugins.clojure.InspectClojureSensor.buildKibitLintProperties(InspectClojureSensor.java:128)
	at org.sonar.plugins.clojure.InspectClojureSensor.analyse(InspectClojureSensor.java:100)
	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:57)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:49)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:78)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:175)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:262)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:257)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:247)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:118)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:117)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)

INFO: ●▬▬▬▬▬▬▬▬▬● Saving measures ●▬▬▬▬▬▬▬▬▬●
[...]
```

**Comment by zmsp** [comment]
Will look at it thanks.

**Comment by zmsp** [comment]
fixed.

**Comment by n2o** [comment]
Thanks for your work!
I am still experiencing the same exception, only the line numbers changed a bit:

```
INFO: ●▬▬▬▬▬▬▬▬▬● Running Kibit ●▬▬▬▬▬▬▬▬▬●
ERROR: ▂▃▅▇█▓▒░ KIBIT IO EXCEPTION  ░▒▓█▇▅▃▂
java.lang.NullPointerException: null
	at java.lang.String.contains(String.java:2133)
	at org.sonar.plugins.clojure.InspectClojureSensor.buildKibitLintProperties(InspectClojureSensor.java:126)
	at org.sonar.plugins.clojure.InspectClojureSensor.analyse(InspectClojureSensor.java:98)
	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:57)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:49)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:78)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:175)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:262)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:257)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:247)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:118)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:117)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
```

**Comment by zmsp** [comment]
Should be fixed on 2a9b9e9a2052d4469699ce3200dfbaf1096ed4f7 I didn't test it very well.
